import { SuburbData } from './types';

export const SUBURBS_DATA: SuburbData[] = [
  {
    name: 'Rockingham',
    slug: 'rockingham',
    soilComposition: 'Coastal sands over limestone (Quindalup/Safety Bay).',
    localHeadache: 'High risk of saltwater intrusion and iron staining in the eastern pockets.',
    councilLink: 'https://rockingham.wa.gov.au/community/sustainability-and-environment/water-management',
    landmark: 'Penguin Island / Foreshore',
    ironRisk: 'High',
    typicalDepth: '10m - 18m',
    waterQualityNotes: 'Elevated salinity and saltwater intrusion margins near Penguin Island/Foreshore, coupled with iron staining in eastern sandy pockets.',
    regulatoryBody: 'City of Rockingham Water Sustainability'
  },
  {
    name: 'Baldivis',
    slug: 'baldivis',
    soilComposition: 'Spearwood sands (west) & Bassendean sands (east); distinct clay pockets.',
    localHeadache: 'High iron staining (causing deep rust discoloration) and highly variable water yield.',
    councilLink: 'https://rockingham.wa.gov.au/community/sustainability-and-environment/water-management',
    landmark: 'Baldivis Children’s Forest',
    ironRisk: 'High',
    typicalDepth: '18m - 32m',
    waterQualityNotes: 'Localized clay layers require premium slotted casing screen setups to prevent silting.',
    regulatoryBody: 'City of Rockingham Sustainability Team'
  },
  {
    name: 'Piara Waters',
    slug: 'piara-waters',
    soilComposition: 'Southern River sands over thin, dense clay layers.',
    localHeadache: 'Severe iron staining, solid coffee rock obstruction, and low groundwater yield.',
    councilLink: 'https://www.armadale.wa.gov.au/waterwise-council',
    landmark: 'Piara Waters Pavilion',
    ironRisk: 'Severe',
    typicalDepth: '14m - 24m',
    waterQualityNotes: 'Exceptional rust-staining hazard. Acidic water requiring heavy-duty iron precipitation treatment.',
    regulatoryBody: 'City of Armadale Waterwise Council'
  },
  {
    name: 'Canning Vale',
    slug: 'canning-vale',
    soilComposition: 'Bassendean sands with thick peaty clay pockets.',
    localHeadache: 'Significant iron staining, highly acidic groundwater, and rapid oxide buildup.',
    councilLink: 'https://www.canning.wa.gov.au/residents/environment-and-sustainability/waterwise-council',
    landmark: 'Ranford Park',
    ironRisk: 'High',
    typicalDepth: '16m - 28m',
    waterQualityNotes: 'Low pH values lead to accelerated corrosion of copper pipes and fittings. Submersible brass recommended.',
    regulatoryBody: 'City of Canning Waterwise Environment'
  },
  {
    name: 'Wellard',
    slug: 'wellard',
    soilComposition: 'Bassendean sands with intermittent clay bands and wetland sediments.',
    localHeadache: 'Severe iron staining, extremely low pH (high acidity), and distinct Hydrogen Sulfide (H2S) organic odor.',
    councilLink: 'https://www.kwinana.wa.gov.au/city-life/sustainability-and-water',
    landmark: 'Wellard Square',
    ironRisk: 'Severe',
    typicalDepth: '18m - 35m',
    waterQualityNotes: 'Rotten egg odors common. Aeration systems or sand filters strongly recommended for pristine retic.',
    regulatoryBody: 'City of Kwinana Environmental Division'
  },
  {
    name: 'Bertram',
    slug: 'bertram',
    soilComposition: 'Predominantly deep Bassendean sands.',
    localHeadache: 'High iron content leading to heavy staining on limestone blocks, retaining walls, and dark fences.',
    councilLink: 'https://www.kwinana.wa.gov.au/city-life/sustainability/water',
    landmark: 'Bertram Oval',
    ironRisk: 'High',
    typicalDepth: '15m - 28m',
    waterQualityNotes: 'Frequent iron filing debris. Requires double-washing screens to retain submersible pump capacity.',
    regulatoryBody: 'City of Kwinana Local Council'
  },
  {
    name: 'Atwell',
    slug: 'atwell',
    soilComposition: 'Bassendean sands underlaid by high shallow water tables.',
    localHeadache: 'Significant iron oxide staining, slimy iron bacteria blockages, and potential organic staining.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Waste/Water-and-Sustainable-Living',
    landmark: 'Atwell Reserve',
    ironRisk: 'High',
    typicalDepth: '12m - 22m',
    waterQualityNotes: 'Occasional jelly-like biological growth. Requires chemical shocking or deep bore cleaning.',
    regulatoryBody: 'City of Cockburn Conservation Officers'
  },
  {
    name: 'Aubin Grove',
    slug: 'aubin-grove',
    soilComposition: 'Fine-grained Bassendean sands.',
    localHeadache: 'Rust-colored iron staining and variable yield close to adjacent wetland boundaries.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Waste/Water-and-Sustainable-Living',
    landmark: 'Radiata Park',
    ironRisk: 'Moderate',
    typicalDepth: '14m - 26m',
    waterQualityNotes: 'Delicate water-bearing layer. Slow-running submersibles prevent drawing boggy silt.',
    regulatoryBody: 'City of Cockburn Environmental Services'
  },
  {
    name: 'Success',
    slug: 'success',
    soilComposition: 'Bassendean coastal sands.',
    localHeadache: 'Heavy iron staining on garden pathways, along with localized sulfurous smell and fine silt particles.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Waste/Water-and-Sustainable-Living',
    landmark: 'Wentworth Park',
    ironRisk: 'High',
    typicalDepth: '15m - 27m',
    waterQualityNotes: 'Iron sulfide reactions can generate odor. Standard filtration mitigates the metallic smell perfectly.',
    regulatoryBody: 'City of Cockburn Water Management'
  },
  {
    name: 'Beeliar',
    slug: 'beeliar',
    soilComposition: 'Spearwood sands consisting of yellow sand over solid limestone deposits.',
    localHeadache: 'Hard water scale deposits, alkaline pH, and moderate iron oxide staining.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Waste/Water-and-Sustainable-Living',
    landmark: 'Beeliar Regional Park',
    ironRisk: 'Moderate',
    typicalDepth: '22m - 40m',
    waterQualityNotes: 'Strong water flow from aquifer. Hard water requires heavy duty anti-scaling sprinklers.',
    regulatoryBody: 'City of Cockburn Environmental Division'
  },
  {
    name: 'Coogee',
    slug: 'coogee',
    soilComposition: 'Spearwood coastal white and yellow sands over hard limestone caves.',
    localHeadache: 'High salinity intrusion risks, heavy calcium alkalinity, and calcium scaling.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Sustainability/Waterwise-Council',
    landmark: 'Coogee Beach',
    ironRisk: 'Minimal',
    typicalDepth: '8m - 18m',
    waterQualityNotes: 'Bores MUST be shallow and low draught to draw sweet water off the top of the salt wedge.',
    regulatoryBody: 'City of Cockburn Waterwise Team'
  },
  {
    name: 'Cockburn Central',
    slug: 'cockburn-central',
    soilComposition: 'Central flat coastal plain sand matrix (Bassendean sands).',
    localHeadache: 'Poor phosphorus retention, highly acidic water, and moderate rust stain threats.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Sustainability/Waterwise-Council',
    landmark: 'Cockburn ARC',
    ironRisk: 'Moderate',
    typicalDepth: '16m - 30m',
    waterQualityNotes: 'Low buffering capacity. Ensure all alloy or iron pipe parts are upgraded to poly/stainless steel.',
    regulatoryBody: 'City of Cockburn Water Conservation'
  },
  {
    name: 'Hammond Park',
    slug: 'hammond-park',
    soilComposition: 'Deep grey and white Bassendean sands over grey clay blankets.',
    localHeadache: 'Highly acidic groundwater, rapid filter wear, and poor naturally occurring nutrient retention.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Sustainability/Waterwise-Council',
    landmark: 'Botany Park',
    ironRisk: 'Moderate',
    typicalDepth: '18m - 34m',
    waterQualityNotes: 'Corrosive water can eat brass impellers. Use thermoplastic or titanium submersibles.',
    regulatoryBody: 'City of Cockburn Urban Compliance'
  },
  {
    name: 'Harrisdale',
    slug: 'harrisdale',
    soilComposition: 'Bassendean sands transitioning rapidly to Southern River boggy soils.',
    localHeadache: 'High rust staining (iron oxide), highly acidic water tables, and mild H2S swamp odours.',
    councilLink: 'https://www.armadale.wa.gov.au/waterwise-council',
    landmark: 'Heron Park',
    ironRisk: 'High',
    typicalDepth: '15m - 26m',
    waterQualityNotes: 'Heavy iron concentrations. Filter bypass plumbing is ideal for lawn and decorative brick segments.',
    regulatoryBody: 'City of Armadale Council Inspectors'
  },
  {
    name: 'Southern River',
    slug: 'southern-river',
    soilComposition: 'Southern River coarse sands overlapping Guildford clay belts.',
    localHeadache: 'High red iron staining, clay sludge clogging filters, and highly patchy water yield.',
    councilLink: 'https://www.gosnells.wa.gov.au/environment-and-sustainability/waterwise-initiatives',
    landmark: 'Sutherlands Park',
    ironRisk: 'High',
    typicalDepth: '12m - 25m',
    waterQualityNotes: 'Flow rate can stall if bore is positioned directly inside clay. Precision placement is key.',
    regulatoryBody: 'City of Gosnells Waterwise Team'
  },
  {
    name: 'Armadale',
    slug: 'armadale',
    soilComposition: 'Darling Scarp outcrop composed of granite, hard laterite rock, and Guildford clay.',
    localHeadache: 'Extremely tough drilling, low or completely unproductive water yields, and steep rock layers.',
    councilLink: 'https://www.armadale.wa.gov.au/waterwise-council',
    landmark: 'Minnawarra Park',
    ironRisk: 'Moderate',
    typicalDepth: '30m - 60m',
    waterQualityNotes: 'Very hard rock strata. Requires rotary hammer or diamond-head drill rigs. Water often of superior purity.',
    regulatoryBody: 'City of Armadale Environment Unit'
  },
  {
    name: 'Kelmscott',
    slug: 'kelmscott',
    soilComposition: 'Darling Scarp rocky slopes underlaid by dense plastic Guildford clay.',
    localHeadache: 'Highly patchy groundwater pockets, clay clogging, low yield, and microscopic iron bacteria.',
    councilLink: 'https://www.armadale.wa.gov.au/waterwise-council',
    landmark: 'Rushton Park',
    ironRisk: 'Moderate',
    typicalDepth: '25m - 50m',
    waterQualityNotes: 'Presence of iron bacteria can clog slots. Annual chemical wash recommended.',
    regulatoryBody: 'City of Armadale Sustainability Desk'
  },
  {
    name: 'Kwinana',
    slug: 'kwinana',
    soilComposition: 'Spearwood yellow sands transitioning to coarse Bassendean sands.',
    localHeadache: 'Iron staining on brick facades and hard water deposits in localized limestone depressions.',
    councilLink: 'https://www.kwinana.wa.gov.au/city-life/sustainability/water',
    landmark: 'Kwinana Adventure Park',
    ironRisk: 'Moderate',
    typicalDepth: '18m - 30m',
    waterQualityNotes: 'Reliable water output. Monitor carbonate buildup on irrigation nozzle jets to save pump life.',
    regulatoryBody: 'City of Kwinana Water Management Group'
  },
  {
    name: 'Spearwood',
    slug: 'spearwood',
    soilComposition: 'Spearwood sands bound by deep, prominent limestone caprock layers.',
    localHeadache: 'High water alkalinity, fast sprinkler nozzles clogging (calcium scaling), but exceptionally high yield.',
    councilLink: 'https://www.cockburn.wa.gov.au/Environment-and-Waste/Water-and-Sustainable-Living',
    landmark: 'Manning Park',
    ironRisk: 'Minimal',
    typicalDepth: '20m - 38m',
    waterQualityNotes: 'Outstanding flow rates. Water is rich in calcium but virtually free of iron staining. Ideal for reticulation.',
    regulatoryBody: 'City of Cockburn Environment'
  },
  {
    name: 'Byford',
    slug: 'byford',
    soilComposition: 'Heavy Guildford clays, gravelly Scarp transitional earths, and rocky granite bands.',
    localHeadache: 'Clay-clogged slot filters, extremely slow recovery times, low bore yield, and high drilling wear.',
    councilLink: 'https://www.sjshire.wa.gov.au/environment-and-sustainability/waterwise-council-program',
    landmark: 'Bill Hicks Reserve',
    ironRisk: 'High',
    typicalDepth: '28m - 55m',
    waterQualityNotes: 'Clay swells can crimp sub-standard bore casing. We utilize schedule 12 heavy duty casing exclusively.',
    regulatoryBody: 'Shire of Serpentine Jarrahdale Conservation'
  }
];

export const GENERAL_REVIEWS = [
  { author: "Damian H. - Rockingham", rating: 5, text: "Excellent prompt service after my coastal pump started sucking air. Solved the salinity issue in an afternoon. Outstanding local knowledge.", date: "April 2026" },
  { author: "Tracey L. - Wellard", rating: 5, text: "The team fixed my rusted-up submersible and added an iron treatment system. No more red stains on our cream brick wall! Outstanding work.", date: "May 2026" },
  { author: "Marcus S. - Byford", rating: 5, text: "Most drillers said no water here because of the clay. Perth BoreWater specialists successfully drilled past the basalt layer and tapped into an awesome spring.", date: "March 2026" },
  { author: "Fiona G. - Canning Vale", rating: 5, text: "Quick response for our reticulation wiring fault. Clear advisory about acid build-up.", date: "May 2026" },
];
