export interface SuburbNarrative {
  regionalOutlook: string;
}

export const MASTER_SUBURB_NARRATIVES: Record<string, SuburbNarrative> = {
  rockingham: {
    regionalOutlook: `Rockingham’s hydro-geological profile is dominated by the Quindalup Dune System, characterized by highly permeable calcareous sands over deep limestone foundations. While this allows for high-yield drilling and rapid recharge, it presents a critical 'Salinity Sensitivity' threshold. Proximity to the Rockingham Foreshore and the Indian Ocean makes domestic bores highly susceptible to saltwater intrusion if drawdown levels are not precisely managed. Our approach here focuses on 'Surgical Depth'—drilling deep enough to secure consistent flow but maintaining a safe buffer from the saline wedge. We utilize Class 12 high-pressure PVC casing to withstand the limestone abrasions common in the 6168 corridor. Homeowners should prioritize annual valve tracking and flow-rate audits to prevent iron-oxide staining, which is moderate in this region but can escalate if system pressure drops. By keeping the intake well above the brackish interface, we leverage the natural sand filtration to supply clear, salt-safe groundwater. This ensures that domestic irrigation system demands are fully met while keeping the garden free from salt burn and protecting our clients' outdoor investment from calcium buildup.`
  },
  baldivis: {
    regionalOutlook: `Baldivis sits on a complex transition zone where the Spearwood Sands of the west meet the Bassendean Dune System of the east. This creates a 'Variable Soil Matrix' that requires expert rig selection. The primary technical challenge in the 6171 area is the high iron-oxide concentration found within the coffee-rock layers. If a bore is not correctly screened and filtered, it can result in the rapid orange-staining of fences and brickwork. Our Baldivis-specific installations utilize advanced stain-stopper intake units and high-efficiency submersible pumps. Because Baldivis is a high-growth area with hundreds of new bores active, correctly calculating the water table depth (typically 18m-32m) is essential to avoid 'Dry-Run' motor burnout. We specialize in 'Success-First' drilling, ensuring your system is engineered for the specific moisture-retention properties of the local sand. By navigating the alternating clay bands and fine quartz sands with tailored slot screens, we ensure a lifetime of silt-free, high-volume flow. This customized approach keeps your turf deep-green and your pathways clean from the common rust discoloration that plagues standard, uncollared regional bores.`
  },
  'piara-waters': {
    regionalOutlook: `Piara Waters represents one of the most technical drilling challenges in the Southern Corridor. The region is defined by the Southern River Sands, which sit over thin, dense clay layers. This 'Layered Substrate' often causes iron-staining 'Hotspots.' In postcode 6112, we see the most aggressive iron-oxide accumulation in Perth, frequently turning driveways and pathways a deep rust color within weeks of a new bore activation. Precision 'Stain Science' is non-negotiable here. Our solution in Piara Waters involves multi-stage filtration and the installation of chemical dosing units to neutralize iron before it hits the surface. We also monitor for 'Low-Yield' pockets where clay lenses can restrict water flow, ensuring your submersible pump is sized correctly so it doesn't struggle against the local geology. Furthermore, the solid coffee rock layers present in the suburb require heavy-duty rotary-percussion drill rigs to pierce during construction. We make sure that our bore depth reaches the sweet water-bearing aquifer below the clay, effectively bypassing the shallow swampy seepage to provide a pristine, odor-free, high-capacity supply.`
  },
  'canning-vale': {
    regionalOutlook: `Canning Vale is situated within the Bassendean Sand system, known for its deep, leachy sands and peaty wetland pockets. This geology results in a high water table but also brings a specific 'Acidity Risk' to pumping equipment. The presence of organic matter in the 6155 aquifer can lead to the build-up of hydrogen sulfide (H2S), often identified by a local 'sulfur smell.' Our Canning Vale service focuses on 'Atmospheric Degassing' and high-grade stainless steel components that resist acidic corrosion. With deep residential lots and mature gardens, the 6155 corridor has some of the highest bore usage in Perth. We use precision mapping to locate solenoid valves tucked under dense foliage, ensuring your reticulation system and bore pump are working in perfect harmony with the high-transpiration needs of the local landscaping. To safeguard against the low pH levels that rapidly corrode standard copper piping and cheap pump fittings, we recommend heavy-duty thermoplastic impellers and bronze submersibles. This custom configuration delivers stable pressure and smooth operation, keeping iron oxide accumulation to an absolute minimum while safeguarding your garden’s health.`
  },
  wellard: {
    regionalOutlook: `Wellard's unique subsurface geology is characterized by Bassendean sands interspersed with dense clay bands and rich swampy wetland deposits. This layout creates two major operational hurdles for domestic water bore owners in the 6170 zone: high concentrations of iron oxide and extremely low pH levels, which point to acidic groundwater. This acidity not only accelerates the corrosion of standard metals but also reacts with dissolved organic matter to release a distinct hydrogen sulfide (H2S) gas, creating an unpleasant rotten-egg odor. To counter these challenges, our Wellard drilling division deploys specialized corrosion-resistant stainless steel and polymer casings. We implement advanced aeration and hydrogen sulfide venting systems during the screening phase. By precisely targeting our drilling depth between 18 meters and 35 meters, we bypass the highly acidic shallow pockets and draw from a cleaner, more alkaline layer of the local aquifer. This strategic positioning, coupled with our iron-precipitation filtration setups, guarantees that your household reticulation system runs clean, scent-free, and stain-safe, keeping your lawns green and your perimeter limestone walls perfectly unstained.`
  },
  bertram: {
    regionalOutlook: `Bertram sits on deep, fine-grained Bassendean sands, which present a highly predictable but challenging water table. While water is plentiful in the 6167 aquifer, the primary issue is the incredibly high iron content. Water bore systems that are improperly installed quickly coat local properties—including expensive limestone brick walls, wooden fences, and concrete driveways—in a deep, unsightly orange-brown rust. Furthermore, fine iron filings and biological silts tend to clog standard sand screens, restricting flow and putting immense back-pressure on the submersible pump. Our Bertram drilling methodology is strictly engineered for these conditions. We install double-washing screens to retain the fine sands while preventing pump siltation. We match this with custom-sized high-flow pumps to sustain correct irrigation pressure. By keeping water velocities through the screen at critical non-turbulent levels, we limit the oxidation of iron within the well itself. This specialized approach ensures that the water remains in liquid form until it leaves the sprinklers, reducing the immediate staining impact and ensuring your system operates efficiently with minimal maintenance for decades.`
  },
  atwell: {
    regionalOutlook: `Atwell is located in a hydro-geological zone characterized by highly permeable Bassendean sands resting over a shallow, abundant water table. Pumping water here is relatively easy, but the 6164 aquifer carries a high concentration of dissolved iron, as well as a risk of biological iron-bacteria growth. This bacteria forms a sticky, jelly-like brown slime that clings to the inside of bore casings, submersible motors, and reticulation valves. Over time, this slime restricts flow, clogs sprinkler nozzles, and produces a foul swampy odor. To address this unique biological hazard, our Atwell team utilizes advanced anti-bacterial bore casings and offers specialized chemical shock-treatment services to keep the well sterilized. We drill to a precise depth of 12 to 22 meters to avoid drawing directly from the stagnant swampy margins of neighboring wetland systems. Our bespoke bore builds feature high-capacity sand screens and heavy-duty, self-cleaning solenoids. This sophisticated setup keeps the sticky bacterial residue at bay, ensuring your reticulation runs with constant, crisp pressure and keeping your fences free of both biological odors and rust-red stains.`
  },
  'aubin-grove': {
    regionalOutlook: `Aubin Grove's local geography features fine-grained Bassendean sands situated near highly delicate wetland boundaries. This proximities mean that while groundwater is easily reached at depths between 14 and 26 meters, drawing water too aggressively can yank boggy silts and peaty organic matter right into your domestic system. Silt infiltration is disastrous, acting as an abrasive that destroys pump impellers and completely blocks domestic irrigation systems in the 6164 postal region. To mitigate this risk, we design Aubin Grove bore systems with ultra-fine, precision-slotted slot screens and wrap them in a multi-layered gravel pack. We also recommend slow-running, multi-stage submersible pumps that gently extract groundwater without creating high-velocity turbulences. This maintains the natural sand filtration around the casing. Additionally, we treat the moderate iron staining risk in this region by setting the pump intake at a scientifically calculated level to draw from the most oxygen-starved, and therefore iron-stable, pocket of the aquifer. The result is a clean, reliable water supply that keeps your gardens pristine and your pump running smoothly.`
  },
  success: {
    regionalOutlook: `Success occupies a coastal plain plain characterized by Bassendean sands, which create a highly accessible but tricky groundwater aquifer. Homeowners in the 6164 area frequently encounter persistent iron staining and a distinct, sulfurous metallic odor. This is caused by iron sulfide chemical reactions occurring in the transition zone between sandy soil and deeper peaty clays. Cheaply installed bores in Success often pump out fine silt, which quickly ruins solenoid valves and leads to dry-spot lawns. Our Success-focused installation designs resolve these issues at the source. We utilize heavy-density, precision-machined plastic components that resist acidic corrosion. We also incorporate advanced degassing slots into our wellheads to vent volatile gases before the water enters your irrigation conduits. Our drilling team structures each well with a tailored casing depth of 15 to 27 meters, ensuring we penetrate deep enough to draw from stable, sand-filtered water tables. This meticulous approach eliminates the rotten-egg smell and restricts the iron oxidation process, ensuring that your automated garden retic works beautifully without leaving unsightly rust blemishes on your pathways.`
  },
  beeliar: {
    regionalOutlook: `Beeliar’s hydrology is built upon the yellow Spearwood Dune System, which sits over expansive, solid limestone formations. Drilling here is highly reliable, with water tables typically found at depths of 22 to 40 meters. However, the prominent limestone matrix means that the groundwater has high alkalinity and is packed with calcium carbonate. Homeowners in the 6164 postcode face a constant battle against hard water scale. When this highly mineralized water evaporates, it leaves behind a stubborn white, chalky residue that coats leaves, blocks sprinkler nozzles, and builds up as scale inside pumps and solenoid valves. To tackle this, our Beeliar drilling and maintenance services focus on advanced scale-prevention configurations. We install high-head submersible pumps designed to maintain constant pressure, which prevents calcium from precipitating within your plumbing line. We also utilize heavy-duty, scale-resistant sprinkler valves and recommend specific waterise nozzle sizes that minimize misting. This ensures that the water is applied directly to your turf as large droplets, reducing evaporation-based calcification and keeping your gardens healthy and white-spots free.`
  },
  coogee: {
    regionalOutlook: `Coogee is a scenic coastal suburb defined by Spearwood white and yellow sands underlaid by incredibly complex, water-cut limestone caverns. Water is highly accessible at shallow depths of 8 to 18 meters, but the extreme proximity to Coogee Beach creates a serious, ever-present risk of saltwater intrusion. If a bore is drilled even a single meter too deep, or if the pump is oversized and draws water too rapidly, it will pull brackish, salty ocean water into the well. This high salinity quickly kills lawns, corrodes irrigation fittings, and leaves a white salt crust on driveways. Our Coogee drilling philosophy is centered on 'Skimming Technology.' We design shallow, wide-diameter wells that gently draw sweet, fresh rainwater from the very top of the freshwater lens. We install low-draught, variable-frequency drive (VFD) pumps that slowly ramp up speed, preventing the turbulent 'up-coning' of the underlying salt wedge. By combining this precise depth control with high-grade, corrosion-immune Class 12 PVC and marine-grade stainless steel casings, we deliver safe, long-lasting freshwater bores that never compromise Coogee's coastal soils.`
  },
  'cockburn-central': {
    regionalOutlook: `Cockburn Central is located on a flat sand plain comprised of the Bassendean Dune System, where the groundwater tables are shallow but chemically unstable. The local aquifer in the 6164 corridor lacks natural buffering, leading to highly acidic water that has a poor capacity to retain essential nutrients like phosphorus. This low pH is highly corrosive, quickly eating through brass impellers, copper pipes, and standard garden fittings, while also carrying a moderate threat of red iron rust staining. At Perth BoreWater, we customize our Cockburn Central bore installations to prevent these acidity-related issues. We construct our systems using specialized thermoplastic or high-grade titanium submersibles that are entirely immune to acid-induced wear. We replace all metal connection points with high-strength polyethylene fittings. Our drilling process targets depths of 16 to 30 meters to secure a consistent flow from waterwise, sand-filtered sand layers. This ensures that your system maintains excellent pressure without leaching heavy metals or causing rusty run-off, helping you preserve your modern landscape design with an eco-safe, stable, and highly durable reticulation system.`
  },
  'hammond-park': {
    regionalOutlook: `Hammond Park sits on deep, grey-white Bassendean sands that sit directly over dense, impermeable grey clay blankets. This 'Double-Layer' hydro-geology creates a perched water table, making water highly accessible at depths of 18 to 34 meters. However, the water in the 6164 postcode is highly acidic and naturally low in vital minerals, meaning it readily dissolves iron and other metals from the soil. This leads to accelerated wear on standard pump components and leaves a light brown stain on light-colored walls and fences. Our Hammond Park services are designed to overcome this aggressive chemical profile. We use corrosion-immune, heavy-walled PVC casings and high-durability polymer impellers that can handle acidic water with ease. To prevent clay particles from entering the well and silting up your system, we apply a specialized micro-mesh sand screen coupled with a washed silica gravel pack. This careful engineering keeps your pump running at peak efficiency, prevents premature motor failure, and delivers high-flow, clean water that nourishes your garden without causing corrosive damage to your reticulation valves.`
  },
  harrisdale: {
    regionalOutlook: `Harrisdale is positioned in a rapid geological transition zone, where the deep dune sands of the Bassendean System shift into the boggy, peaty soils of the Southern River basin. This complex geology in the 6112 postcode leads to extremely high concentrations of dissolved iron oxide and a strong risk of swampy, organic hydrogen sulfide (H2S) odors from the shallow groundwater. Homeowners who install cheap, standard bores quickly find their limestone walls, paved walkways, and gardens coated in a heavy, red-brown rust stain. To solve this, our Harrisdale bore systems are custom-built to target the safest water-bearing zones. We drill to a precise depth of 15 to 26 meters, using specialized geological logging to locate clean, clay-free sand pockets. We install advanced aeration caps and multi-phase iron-reduction screens that filter out iron particles before they can oxidize on your property. This proactive design eliminates the unpleasant sulfur smell and protects your outdoor living areas from unsightly staining, giving you a crystal-clear, high-volume water source that keeps your lawns beautifully green of all seasons.`
  },
  'southern-river': {
    regionalOutlook: `Southern River contains a mixture of coarse sands and deep, dense clay belts belonging to the Guildford Formation. This creates a highly challenging hydrologic environment where water yields are extremely variable across short distances. In the 6110 area, clay sludge is a major threat, frequently finding its way inside bore wells, where it clogs fine sand screens and reduces water flow to a trickle. Compounding this is a high concentration of dissolved iron, which causes severe red-orange staining on home exteriors. To conquer these hurdles, our Southern River drilling process is exceptionally precise. We carry out detailed site-specific geological test-drilling to locate water-bearing sand channels within the clay. We utilize specialized double-tough, precision-slotted casing screens wrapped in a thick, custom-graded gravel pack to filter out all fine clay silts. Should your flow rate decrease, our local team provides high-pressure well-flushing and chemical iron-remediation services. This comprehensive engineering ensures that your bore maintains a robust water flow while keeping your garden and masonry free of rust.`
  },
  armadale: {
    regionalOutlook: `Armadale's geography sits directly on the slopes of the Darling Scarp, where the terrain is dominated by hard granite rock, tough laterite gravel, and dense Guildford clay. Drilling water bores in the 6112 postcode is notoriously difficult, requiring specialized heavy-duty rotary-hammer and diamond-head drill rigs to cut through the solid rock strata. Groundwater can be highly elusive, often requiring us to drill to deep depths of 30 to 60 meters to locate productive water-bearing rock fractures. However, once reached, the water quality in Armadale is typically of outstanding purity, with minimal iron content and low salinity. Our Armadale drilling team is uniquely equipped with the heavy equipment and engineering expertise needed to succeed in this formidable terrain. We utilize ultra-strong, schedule 12 thick steel and heavy PVC casings that can withstand the crushing forces of moving clay and rock layers. We specialize in locating fracture zones with advanced geological mapping, delivering high-performance, long-lasting rock bores that provide a virtually unlimited supply of clean, pure water for your home.`
  },
  kelmscott: {
    regionalOutlook: `Kelmscott features a complex geology where the steep, rocky slopes of the Darling Scarp soften into dense, plastic clays of the Guildford plain. This transition makes the groundwater table in the 6111 area highly patchy and unpredictable, with clay-silting being a major threat to standard bore installations. Furthermore, the local aquifer often hosts active iron bacteria. This harmless but highly problematic microorganism feeds on dissolved iron, creating a thick, sticky brown slime that clogs casing slots, coats submersible motors, and restricts water yield. To maintain clean water flow in Kelmscott, we customize each bore with specialized anti-bacterial casings and high-pressure, self-flushing screens. We drill to depths of 25 to 50 meters, cutting past the sticky clay bands to tap into clean, gravel-filtered aquifers. We also provide annual chemical wash-outs to keep iron bacteria from accumulating. This meticulous design prevents pump overheating and protects your reticulation system from mud and slime, delivering a strong, reliable flow of crisp groundwater for your garden.`
  },
  kwinana: {
    regionalOutlook: `Kwinana has a favorable hydrologic profile characterized by yellow Spearwood sands that gradually transition into the coarse sands of the Bassendean Dune System. Domestic water bores in the 6167 area are highly productive, with stable water tables usually reached at reliable depths of 18 to 30 meters. However, homeowners still face moderate iron staining risks on light-colored brick home facades, as well as calcium carbonate scaling in areas underlaid by limestone depressions. If left unmanaged, calcium and iron buildup will clog irrigation sprays, leading to uneven watering and dry patches on your lawn. Our Kwinana drilling and maintenance division optimizes systems for long-term, high-yield efficiency. We install scale-resistant pop-up sprinklers and configure our systems with high-efficiency submersible pumps that maintain stable water pressure. We also adjust our well designs to extract water from the cleanest zones of the sandy aquifer. This tailored approach keeps mineral deposits to an absolute minimum, ensuring your garden stays perfectly hydrated and your pathways remain completely free of unsightly iron stains.`
  },
  spearwood: {
    regionalOutlook: `Spearwood’s hydrology is defined by its deep, prominent limestone caprock, which is covered by a layer of rich, yellow Spearwood sands. Water bores in this coastal corridor are exceptionally high-yielding, tapping into massive, fast-flowing aquifers at depths of 20 to 38 meters. The water in the 6163 postcode is virtually free of the red iron staining that plagues other Perth suburbs, making it ideal for watering turf and garden beds. However, the water is highly alkaline and rich in dissolved calcium, making calcium scaling a major operational challenge. As the water evaporates, it leaves behind a hard white lime crust that blocks sprinkler spray heads and coats plant foliage. Our Spearwood-specific installations focus on maintaining high flow rates and uniform coverage. We utilize high-pressure pumps and heavy-duty, scale-resistant polymer valves that prevent mineral crystallization inside your irrigation line. Our designs ensure that water is applied cleanly and efficiently, protecting your landscaped pathways from chalky white residue while providing a highly abundant water source.`
  },
  byford: {
    regionalOutlook: `Byford is located at the base of the Darling Scarp, where the underground geology consists of heavy, expanding Searle clays, gravelly transitional soils, and hard granite rock bands. Drilling in the 6122 area is highly demanding, as clay layers tend to swell and can easily crush standard, light-duty bore casings. In addition, these dense clays act as barriers that restrict groundwater movement, resulting in very slow recovery times and low yields for typical domestic wells. To ensure water bore success in Byford, our team uses heavy-duty, high-strength Class 12 PVC and thick-walled steel casings that easily resist geological pressure. We install extra-long, precision-cut slot filters and pack them with fine, washed silica gravel. This helps maximize water entry and keeps fine mud particles out of your system. Our drillers typically target deep aquifers between 28 and 55 meters to secure a reliable, silt-free flow. This robust construction safeguards your pump from clay-silting and delivers a lasting, clean water supply for your property.`
  }
};

export function getSuburbNarrative(nameOrSlug: string): string {
  if (!nameOrSlug) return "Technical Hydro-Geological Profile: Data Pending Regional Survey.";
  const normalized = (nameOrSlug || '').trim().toLowerCase().replace(/\s+/g, '-');
  const record = MASTER_SUBURB_NARRATIVES[normalized];
  if (record) {
    return record.regionalOutlook;
  }
  // Fallback to human name if slug look-up doesn't match directly
  const rawSubName = (nameOrSlug || '').split('-').map(word => word ? (word.charAt(0).toUpperCase() + word.slice(1)) : '').join(' ');
  return `${rawSubName} Technical Hydro-Geological Profile: Data Pending Regional Survey.`;
}
