export interface SuburbGeologicalProfile {
  headline: string;
  insightParagraph1: string;
  insightParagraph2: string;
  trustSignal: string;
}

export const SUBURB_GEOLOGICAL_DATA: Record<string, SuburbGeologicalProfile> = {
  'rockingham': {
    headline: 'Bore Drilling Challenges in Rockingham: Mastering the Coastal Sand & Limestone Strata',
    insightParagraph1: 'Drilling in Rockingham requires precise handling of the Safety Bay and Quindalup Sand dunes sitting directly on top of rugged limestone shelves. The main technical headache here is navigating the limestone without causing structural vibration to coastal homes or experiencing sudden circulation loss in subterranean cavities. We employ advanced rotary-air drill rigs with custom roller cone bits, allowing us to cleanly bore through shifting sand-to-rock interfaces and seat heavy-duty casing into uniform water-bearing limestone.',
    insightParagraph2: 'To prevent saltwater intrusion and the common local challenge of iron staining in eastern sandy pockets, the depth of each Rockingham bore is metered down to the exact decimeter. We restrict drilling to shallower skimming zones where fresh "sweet" water sits on top of the heavier marine saltwater table, using high-flow slotted PVC screens to avoid drawing fine coastal silt into your reticulation nozzles.',
    trustSignal: 'Whether you’re in a beachfront residence near the Penguin Island / Foreshore area or in the sandy eastern pockets of the suburb, our local crew possesses decades of experience mapping municipal water tables in the 6168 corridor to deliver premium, stain-free groundwater.'
  },
  'baldivis': {
    headline: 'Bore Drilling Challenges in Baldivis: Mastering the Spearwood and Bassendean Transitions',
    insightParagraph1: 'Baldivis features a complex geological transition where the rich, yellow Spearwood sands of the west give way to the fine, quartz-heavy Bassendean dune systems of the east, heavily interspersed with stubborn clay pockets. The chief obstacle for drillers is the high variability in groundwater yield and encountering sticky, consolidated clay bands that clog standard drilling rigs. We utilize specialized heavy-torque augers and polymers to flush the clay out smoothly, preventing friction damage and ensuring a pristine borehole.',
    insightParagraph2: 'Iron contamination is exceptionally high in Baldivis, resulting in the notorious rust-tinted staining on limestone retaining walls and fences. Our custom Baldivis builds incorporate double-washed gravel packs and ultra-fine slotted casing screens that filter out iron-bound clay particles before they are pulled into the pump chamber, preventing localized silting and extending the motor lifespan.',
    trustSignal: 'Whether you’re near the tranquil Baldivis Children’s Forest or located closer to the newer estates in the eastern flats, our technicians know the precise depth of the local water table (ranging from 18m to 32m) to secure maximum flow rate with minimal silt intake.'
  },
  'piara-waters': {
    headline: 'Bore Drilling Challenges in Piara Waters: Mastering the Southern River and Coffee Rock Strata',
    insightParagraph1: 'Piara Waters presents some of the most challenging drilling conditions in Perth\'s Armadale region, characterized by Southern River sands resting above highly dense, iron-rich coffee rock and underlying clay lenses. Penetrating the coffee rock requires immense downward pressure and high-tensile tricone drill bits. Our modern compact rigs deliver this massive torque cleanly, enabling us to break through the hard rock layers without creating excessive sonic vibrations that could disrupt neighboring properties or shift delicate foundations on smaller residential blocks.',
    insightParagraph2: 'The primary concern for local homeowners is the severe iron staining that can paint pathways and gardens red within a few water cycles. To combat this, we drill past the highly contaminated shallow run-off zones to tap into cleaner underlying sand aquifers. We couple this with advanced low-oxygen casing seals that throttle the oxidation process of iron-carbonate before the water is pumped into your reticulation header.',
    trustSignal: 'Whether you’re situated right beside the bustling Piara Waters Pavilion or in the newer surrounding estates, our local team understands the deep hydrological secrets of the 6112 postcode, ensuring your system bypasses the hard coffee rock with complete safety and peak flow.'
  },
  'canning-vale': {
    headline: 'Bore Drilling Challenges in Canning Vale: Mastering the Peaty Bassendean Sand Matrix',
    insightParagraph1: 'The geological blueprint of Canning Vale is dominated by deep Bassendean sands containing thick, decomposing peaty clay pockets. The local headache is highly acidic groundwater that rapidly corrodes standard brass pump components and copper pipes, as well as the presence of hydrogen sulfide (H2S), which releases a rotten-egg organic odor. We handle these acidic, peaty conditions by using heavy-walled, high-grade thermoplastic submersible pumps and chemical-resistant PVC liners that never corrode or lock up.',
    insightParagraph2: 'In addition to acidity, peaty clays tend to slough off and collapse into the wellbore during the drilling process. To prevent this, we apply mud-rotary drilling techniques to stabilize the hole walls temporarily. Once the well reaches its optimum water-bearing sand level, we install dual-filtration gravel shrouds to lock out peaty residues and ensure clear, odor-free water flow.',
    trustSignal: 'Whether your property borders the greenery of Ranford Park or sits deep in the established residential sections of the 6155 corridor, our crew has mapped the highly variable Canning Vale water tables for decades to eliminate acidity risks once and for all.'
  },
  'wellard': {
    headline: 'Bore Drilling Challenges in Wellard: Mastering the Wetland Sediments & Acidic Bassendean Strata',
    insightParagraph1: 'Wellard holds a delicate geological profile where deep Bassendean sands sit mixed with wet organic silts, heavy clays, and ancestral wetland beds. This results in highly acidic, low-pH water tables and severe issues with organic hydrogen sulfide odors and rapid iron oxide buildup. Our high-productivity air-rotary drilling setups easily bypass these clay bands, utilizing premium polymers to lift swamp sediment and clay cuttings to the surface without collapsing the wellbore.',
    insightParagraph2: 'Because Wellard\'s groundwater is highly corrosive to normal metallic alloys, our team exclusively uses chemically-inert titanium and thermoplastic submersible pump assemblies. We also design and install dual-stage aeration systems and specialized catalytic media sand filters, which eliminate the pungent metallic smell and oxidize the dissolved iron safely before the water reaches your lawn.',
    trustSignal: 'Whether your home is a stone\'s throw from Wellard Square or borders the low-lying nature reserves, our technicians possess unparalleled local expertise to size and spec a water bore system tailored to the unique wetland sediment conditions of the 6170 postcode.'
  },
  'bertram': {
    headline: 'Bore Drilling Challenges in Bertram: Mastering the Deep Bassendean Sands Strata',
    insightParagraph1: 'Bertram features deep, permeable Bassendean sands that are excellent for water filtration but heavily laden with dissolved iron. The soft, shifting nature of these sands means that standard wellbores are prone to cave-ins during the drilling phase if the driller is too aggressive. We use specialized temporary steel casing strings to hold the borehole open as we drill, guaranteeing structural integrity of the well prior to seating the permanent Class 12 PVC casing.',
    insightParagraph2: 'The main regional headache in Bertram is the rapid orange-rust staining that occurs on limestone blocks, retaining walls, and dark fences. Our drilling technicians combat this by implementing a larger well-slot configuration combined with high-grade, double-washed river gravel packs. This advanced filtering system keeps fine iron-bound silt locked deep in the aquifer, resulting in cleaner, clearer water discharging into your sprinklers.',
    trustSignal: 'Whether you’re near Bertram Oval or located closer to the Kwinana Freeway borders, our team\'s comprehensive knowledge of local water tables ensures that we hit high-flowing, stain-free aquifers with absolute reliability.'
  },
  'atwell': {
    headline: 'Bore Drilling Challenges in Atwell: Mastering the High Water Table Bassendean Strata',
    insightParagraph1: 'Atwell is characterized by a very shallow water table situated within shifting Bassendean coastal sands. While water is easy to reach (typically at 12m to 22m), the shallow nature of the aquifer makes it an active breeding ground for slimy iron-bacteria colonies. This bio-slime can quickly coat pump impellers, choke slot filters, and cause severe drop-offs in water pressure. We utilize specific high-pressure jetting and shock-chlorination techniques during the final development phase of drilling, eliminating bacteriological presence from day one.',
    insightParagraph2: 'To ensure long-term, high-volume flow under these high water table conditions, our Atwell installations utilize precision laser-slotted screens. By scaling the intake slot dimensions exactly to the local grain size of Atwell\'s grey sand, we prevent the fine grains from squeezing through into the pump, eliminating the risk of costly turbine wear or impeller seizing.',
    trustSignal: 'Whether your garden sits near the popular Atwell Reserve or closer to the local school grounds, our experienced technicians know how to properly seal and vent your shallow bore to prevent iron bacteria and maintain prime domestic water flow.'
  },
  'aubin-grove': {
    headline: 'Bore Drilling Challenges in Aubin Grove: Mastering the Fine Bassendean Sand Strata',
    insightParagraph1: 'Aubin Grove is marked by exceptionally fine-grained, grey Bassendean sands that sit directly adjacent to low-lying wetland boundaries. The chief problem when drilling in Aubin Grove is silting; these delicate, fine-grained sand particles can easily bypass standard slot casings, clogging the main turbine and grinding down the internal plastic impellers of cheap pumps. We prevent this by utilizing premium stainless-steel intake screens wrapper-sleeved in fine-mesh geotextiles, creating an impenetrable barrier against silt.',
    insightParagraph2: 'Because of the proximity to sensitive wetland boundaries, water levels can fluctuate. We calculate your bore depth with a generous safety margin, ensuring that even during the heat of late February, your pump inlet remains submerged in reliable water-bearing sand without pulling up boggy mud or organic detritus from the bottom of the aquifer.',
    trustSignal: 'Whether your property is located right next to Radiata Park or up on the higher sand ridges, our deep familiarity with Aubin Grove\'s delicate soil boundaries guarantees a highly-stable well that is built to last through hot dry summers.'
  },
  'success': {
    headline: 'Bore Drilling Challenges in Success: Mastering the Coast-Adjacent Bassendean Strata',
    insightParagraph1: 'Success is defined by complex coastal-adjacent Bassendean sand formations that hold moderately high levels of dissolved iron and organic sulfur compounds. When drilling in Success, the shifting sandy soils demand highly managed air-pressures during rotary-drill operations to prevent fracturing the weak surface soils. Our state-of-the-art compact drilling rigs use micro-adjustable pneumatic controls to carve out a clean vertical path through Success\'s sandy layers with zero ground disturbance.',
    insightParagraph2: 'The main customer headache is the heavy orange iron oxide staining on garden pathways, alongside a localized sulfurous "rotten-egg" smell. To mitigate these nuisances, we specialize in sealing off the shallow, organic-heavy top-layers and drawing water exclusively from the deeper, cleaner sand aquifers, which naturally filter out organic odors and minimize iron-carbonate concentrations.',
    trustSignal: 'Whether you’re situated around Wentworth Park or near the Cockburn Gateway shopping perimeter, our local team possesses the exact geological maps and historical bore logs to ensure your Success home receives excellent flow with clean, odor-free water.'
  },
  'beeliar': {
    headline: 'Bore Drilling Challenges in Beeliar: Mastering the Spearwood Sand over Limestone Strata',
    insightParagraph1: 'Beeliar sits on a prominent ridge of yellow Spearwood sands that run directly over dense, solid limestone deposits. The primary obstacle for local bore drilling is navigating these limestone rock layers. Standard sand-drilling rigs will simply burn out their bits when they hit Beeliar\'s limestone rock; we utilize high-power hammer-drill rigs equipped with tungsten carbide button bits to slice through the limestone with absolute ease, completing most suburb projects in a single day.',
    insightParagraph2: 'While Beeliar aquifer water is generally free from iron staining, it is rich in dissolved calcium carbonate (hard water). As the water evaporates, it leaves behind a cloudy calcium scale on leaves and windows. We engineered Beeliar-specific bore wells that are drilled deeper into the limestone crevices where water temperature is cooler and calcium is more stable, minimizing scale buildup on your prized garden foliage.',
    trustSignal: 'Whether your property overlooks the pristine Beeliar Regional Park or sits closer to the coastal borders, our drillers possess the specialized rock-boring tools and engineering know-how to deliver a high-yield limestone water well.'
  },
  'coogee': {
    headline: 'Bore Drilling Challenges in Coogee: Mastering the White Sand and Limestone Caves Strata',
    insightParagraph1: 'Drilling in the beautiful coastal suburb of Coogee involves white and yellow Spearwood sands underlaid by highly porous limestone, which contains underground caves and channels. The primary hazard is the massive loss of drill fluid circulation when the bit punctures a limestone cave, along with a high risk of saltwater intrusion due to the immediate proximity of the Indian Ocean. We run specialized case-method drilling to shield these cave passages, maintaining a stable hole pressure at all times.',
    insightParagraph2: 'Because Coogee lies directly on the coast, drawing water too aggressively can pull the marine saltwater wedge inland, destroying lawns and ruining bore equipment. We design specialized low-draught, shallow skimming bores that gently draw sweet, fresh groundwater off the top of the saltwater table, pairing them with variable speed pumps configured to protect the coastal ecology.',
    trustSignal: 'Whether your home is perched on the hills near Coogee Beach or closer to the marina docks, our team has mapped Coogee\'s marine saltwater interfaces for decades, ensuring your coastal bore is legally compliant, secure, and highly productive.'
  },
  'cockburn-central': {
    headline: 'Bore Drilling Challenges in Cockburn Central: Mastering the Flat Sand Plain Matrix Strata',
    insightParagraph1: 'Cockburn Central sits on flat sand plains consisting of a porous Bassendean sand matrix. The main technical headache in this highly built-up urban center is managing drilling operations on tight residential lots where access is heavily restricted. We utilize highly compact, rubber-tracked drilling rigs that can slip through standard garden gates, allowing us to install a high-yield water bore right next to your alfresco area with zero damage to existing paving.',
    insightParagraph2: 'The local groundwater here is highly acidic and has very poor natural mineral buffering, which can cause galvanic corrosion in metallic pump bodies. Our Cockburn Central bore packages utilize premium non-corrosive polymer suction sleeves and solid thermoplastic impellers to ensure your mechanical parts remain completely unaffected by the acidic sand groundwater.',
    trustSignal: 'Whether you’re near the modern Cockburn ARC or in the denser residential grids surrounding the train station, our local crew delivers whisper-quiet drilling services that respect your property boundaries and your neighbors\' peace.'
  },
  'hammond-park': {
    headline: 'Bore Drilling Challenges in Hammond Park: Mastering the Grey Sand and Clay Blanket Strata',
    insightParagraph1: 'Hammond Park features highly absorbent grey and white Bassendean sands that sit directly on top of dense, impermeable grey clay blankets. The presence of these clay blankets blocks the downward flow of water, creating a highly complex aquifer system. Our drillers must use precise hydrological testing to identify the sweet spot between the shallow sand and the sticky clay. Moving too deep into the clay will choke the bore; staying too shallow risks the bore running dry in summer.',
    insightParagraph2: 'Furthermore, the local groundwater is acidic and stripped of nutrients, which accelerates the wear on standard irrigation valves. We combat this by installing specialized chemical-resistant schedule 80 PVC casing and deploying high-performance submersible pumps engineered to resist corrosion, guaranteeing over 20 years of trouble-free operation in Hammond Park\'s soil.',
    trustSignal: 'Whether your house is nestled near Botany Park or sits closer to the southern freeway exits, our local technicians are experts at navigating the shifting clay blankets of the 6164 postcode, supplying your lawns with absolute flow consistency.'
  },
  'harrisdale': {
    headline: 'Bore Drilling Challenges in Harrisdale: Mastering the Bassendean and Southern River Transition Strata',
    insightParagraph1: 'Harrisdale sits on a highly dynamic geological transition zone, where the grey Bassendean sands rapidly collide with the swampy, clay-rich soils of the Southern River network. This results in heavy, sticky mud running throughout the subsoil, which can instantly seize up standard drilling equipment. We use continuous-flight drill augers and high-viscosity bio-degradable drilling fluids to lubricate the drill path, carrying the sticky swamp sediments cleanly out of the wellbore.',
    insightParagraph2: 'Postcode 6112 is notorious for severe iron-oxide staining and toxic organic hydrogen sulfide smells from rotting peat beds. We solve these twin problems by bypassing the contaminated top-soils, drilling down to deeper, clean sand water-bearing channels and sealing off the upper casing sections with expansive bentonite clay plugs to prevent swamp water from leaking into your clean underground supply.',
    trustSignal: 'Whether you live near the family-friendly Heron Park or on the outskirts of the greenbelts, our local team knows exactly where the transition bands lie, delivering top-quality water with pristine clarity and zero offensive odors.'
  },
  'southern-river': {
    headline: 'Bore Drilling Challenges in Southern River: Mastering the Coarse Sands & Guildford Clay Belts',
    insightParagraph1: 'Southern River is characterized by a challenging mixture of coarse, water-saturated Southern River sands that overlap the massive, rock-hard Guildford clay belt. The local headache is highly patchy water yield; if a driller accidentally positions your bore screen directly inside a clay belt, the flow will completely stall. We use down-hole geophysical logging and sand-sampling to locate thin, high-flowing sand veins sandwiched between the thick clay layers, setting our intake filters with millimeter precision.',
    insightParagraph2: 'Because of the heavy clay content, fine clay sludge can migrate into the well screen and choke the pump over time. Our Southern River installations feature a dual-casing design where an outer steel sheath shields the well during drilling. We pack the annular gap with specific coarse quartz gravel to create a robust natural sand filter that keeps the clay out of your water supply permanently.',
    trustSignal: 'Whether your property is located near Sutherlands Park or sits in the newly developed estates, our specialized drilling rigs and experienced geologists ensure that your Southern River bore tapped into the cleanest, highest-flowing aquifer layers available.'
  },
  'armadale': {
    headline: 'Bore Drilling Challenges in Armadale: Mastering the Rock-Hard Darling Scarp Granite Strata',
    insightParagraph1: 'Armadale sits directly on the slopes of the Darling Scarp, where the subsurface is dominated by solid granite, tough laterite rock, and ultra-dense Guildford clay. This is arguably the toughest drilling environment in Perth. Standard water bore rigs cannot make even an inch of progress here; we deploy ultra-heavy-duty pneumatic rotary hammer rigs that crack through rock and granite boulders using diamond-tipped drill bits, allowing us to tap into deep, pristine rock fracture aquifers.',
    insightParagraph2: 'Although drilling into Armadale\'s granite is highly technical, the water quality harvested from these deep rock crevices is remarkably pure, showing almost zero iron-staining or organic odor. Our focus in Armadale is on wellbore structural safety, utilizing heavy-wall Class 18 PVC casing to shield the well against shifting rock pressures and ensure the long-term safety of your home\'s groundwater source.',
    trustSignal: 'Whether you\'re situated near the leafy hills of Minnawarra Park or up on the steep granite ridges of the Scarp, our team has the specialized heavy machinery and diamond-drill technology to conquer Armadale\'s rock and deliver crystal-clear groundwater.'
  },
  'kelmscott': {
    headline: 'Bore Drilling Challenges in Kelmscott: Mastering the Scarp Rocky Slopes & Dense Plastic Clays',
    insightParagraph1: 'Kelmscott\'s geology is defined by rocky Scarp slopes underlaid by highly plastic, swellable Guildford clay beds. This sticky, dense clay acts as a major bottleneck for drilling operations, absorbing water and swelling to pinch or crimp poor-quality bore casings. We prevent this by drilling a oversized borehole and utilizing heavy duty, thick-walled schedule 15 pressure casing that easily resists the massive lateral crushing forces of Kelmscott\'s shifting clay.',
    insightParagraph2: 'Kelmscott also suffers from specialized iron-reducing bacteria that love the warm, iron-rich clays, forming thick gelatinous mats inside pumps. We counteract this by installing custom-welded, corrosion-proof stainless-steel pump housings and treating the completed wellbore with specific non-toxic bio-acids that strip away bacteriological buildup before it can colonize your irrigation nozzles.',
    trustSignal: 'Whether your home is down near the banks of Rushton Park or nestled on the rocky slopes of the foothills, we have the specialized heavy machinery and clay-remediation techniques to ensure your domestic bore operates at peak flow rate year-round.'
  },
  'kwinana': {
    headline: 'Kwinana Bore Drilling Challenges: Mastering the Spearwood yellow to Bassendean transitions',
    insightParagraph1: 'Kwinana\'s subsurface geology transitions from dry yellow Spearwood dune sands into moist, low-lying Bassendean sand plains. The primary technical concern is hitting dense, consolidated coffee-rock bands that exist at the shallow water line. Drilling through these hard, iron-cemented sand layers requires high-torque air-rotary rigs. We utilize specialized drag bits with heavy water injection to lubricate the cut, enabling rapid and vibration-free penetration right through the coffee-rock layer.',
    insightParagraph2: 'The local groundwater in Kwinana can carry moderate iron-staining potential and high calcium hardness. We resolve this by drilling past the shallow water table into the deeper, highly-filtered aquifers. By using a longer, custom-wrapped sand-screen intake, we distribute the pumping pressure over a larger subsurface area, drawing clear, stain-free water that won\'t scale up your paths or rust your home\'s facade.',
    trustSignal: 'Whether you\'re located near the family-favourite Kwinana Adventure Park or in the established residential streets of the suburb, our local drillers utilize tailored well designs built to withstand the unique chemical signatures of the Kwinana industrial-to-residential corridor.'
  },
  'spearwood': {
    headline: 'Bore Drilling Challenges in Spearwood: Mastering the Famous Spearwood Sand and Caprock Strata',
    insightParagraph1: 'Spearwood represents a legendary geological zone, famous for its deep yellow sands sitting directly over incredibly thick, solid limestone caprock layers. While these limestone layers contain some of Perth\'s highest-yielding aquifers, drilling through the solid caprock demands massive mechanical power. We utilize premium hydraulic percussion hammer rigs to crack through the hard limestone barriers, opening up clean, unrestricted water channels that provide exceptional, high-yield flow rates.',
    insightParagraph2: 'The main local headache is not iron staining, but rather extreme calcium carbonate hardness. Hard water from Spearwood\'s limestone can quickly clog up sprinkler nozzles and leave white, crusty calcium deposits on your windows and dark foliage. Our Spearwood bore designs incorporate deeper well paths that capture softer, cleaner under-flows, matching them with high-efficiency wide-orifice nozzles that resist scaling.',
    trustSignal: 'Whether your home is nestled next to the beautiful Manning Park or perched on the coastal slopes, our team\'s specialized limestone drilling experience ensures you get maximum water volume with a rock-solid, durable bore setup.'
  },
  'byford': {
    headline: 'Bore Drilling Challenges in Byford: Mastering the Dense Guildford Clay & Laterite Strata',
    insightParagraph1: 'Byford\'s subsurface is comprised of dense, sticky plastic Guildford clays, gravelly Scarp transitional soils, and hard laterite rock bands. The primary headache for drillers is the clay-clogging of slot filters, slow aquifer recovery times, and intense rig wear. Standard drilling methods fail completely in Byford\'s sticky clay; we deploy specialized high-pressure mud-rotary drilling rigs that liquefy the clay layers as we drill, sweeping the heavy mud out and preventing the well walls from collapses.',
    insightParagraph2: 'Because Byford clay releases water very slowly, standard bore screens will quickly run dry. We overcome this low-yield challenge by installing extra-long, high-capacity screen modules wrapped in porous pea-gravel shrouds. This increases the surface intake area of the bore by over 300%, allowing the surrounding clay to gently seep water into the wellbore and ensuring a non-stop, high-volume flow for your garden.',
    trustSignal: 'Whether your property is situated near the scenic Bill Hicks Reserve or closer to the newer Darling Downs borders, our class-leading clay-penetration technology and custom wellpacks guarantee Byford homeowners a highly reliable groundwater source.'
  }
};
